#!/bin/sh -
# vim: set ts=4:sw=4:et:ai
# Note to self: A secure cat is a gpg enabled cat ;)
# Usage:
# passwords=/home/bob/etc/file.gpg
# export PRIVATE_KEYRING=$passwords
# gpgcat mimi...
gpg=/usr/bin/gpg
version="1.0"
if [ "$1" = "-v" ];
then
	echo "gpgcat version $version"
	echo "Copyright (C) 2024 Etienne Robillard <smart@open-neurosecurity.org>"
	echo "This software is licensed under the General Public License (GPL) version 3.0."
	echo "For more info please see <https://www.gnu.org/>"
	exit 0
fi
if [ "$1" = "--help" ];
then
	echo "Usage: $0 <secret>"
	exit 2
fi
if [ ! -n "$1" ]; then
	echo "Usage: $0 [[--help][-v]] string"
	exit 2
fi
if [ ! -z $PRIVATE_KEYRING ];
then
	${gpg} -d $PRIVATE_KEYRING | grep $1
else
	echo "Error: Please set the 'PRIVATE_KEYRING' variable in your env."
	exit 1
fi
exit 0
